"""add contest models

Revision ID: b707d8612ff5
Revises: 06fbdc620bc7
Create Date: 2026-03-16 08:52:50.342926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b707d8612ff5'
down_revision: Union[str, Sequence[str], None] = '06fbdc620bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', name='contest_status'), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_at < end_at', name='ck_contest_start_before_end'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_status'), 'contests', ['status'], unique=False)
    op.create_index(op.f('ix_contests_title'), 'contests', ['title'], unique=False)
    op.create_table('contest_participations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('has_submitted_entry', sa.Boolean(), nullable=False),
    sa.Column('evaluation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('evaluation_count >= 0', name='ck_contest_participations_evaluation_nonnegative'),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contest_id', name='uq_contest_participations_user_contest')
    )
    op.create_index(op.f('ix_contest_participations_contest_id'), 'contest_participations', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_participations_id'), 'contest_participations', ['id'], unique=False)
    op.create_index(op.f('ix_contest_participations_user_id'), 'contest_participations', ['user_id'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rd', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('comparisons_count', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('comparisons_count >= 0', name='ck_entries_comparisons_count_nonnegative'),
    sa.CheckConstraint('losses >= 0', name='ck_entries_losses_nonnegative'),
    sa.CheckConstraint('rating >= 0', name='ck_entries_rating_nonnegative'),
    sa.CheckConstraint('rd >= 0', name='ck_entries_rd_nonnegative'),
    sa.CheckConstraint('volatility >= 0', name='ck_entries_volatility_nonnegative'),
    sa.CheckConstraint('wins >= 0', name='ck_entries_wins_nonnegative'),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contest_id', name='uq_entries_contest_user')
    )
    op.create_index(op.f('ix_entries_contest_id'), 'entries', ['contest_id'], unique=False)
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('voter_user_id', sa.Integer(), nullable=False),
    sa.Column('entry_a_id', sa.Integer(), nullable=False),
    sa.Column('entry_b_id', sa.Integer(), nullable=False),
    sa.Column('chosen_entry_id', sa.Integer(), nullable=False),
    sa.Column('entry_a_rating_before', sa.Float(), nullable=False),
    sa.Column('entry_b_rating_before', sa.Float(), nullable=False),
    sa.Column('entry_a_rd_before', sa.Float(), nullable=False),
    sa.Column('entry_b_rd_before', sa.Float(), nullable=False),
    sa.Column('entry_a_volatility_before', sa.Float(), nullable=False),
    sa.Column('entry_b_volatility_before', sa.Float(), nullable=False),
    sa.Column('entry_a_rating_after', sa.Float(), nullable=False),
    sa.Column('entry_b_rating_after', sa.Float(), nullable=False),
    sa.Column('entry_a_rd_after', sa.Float(), nullable=False),
    sa.Column('entry_b_rd_after', sa.Float(), nullable=False),
    sa.Column('entry_a_volatility_after', sa.Float(), nullable=False),
    sa.Column('entry_b_volatility_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chosen_entry_id IN (entry_a_id, entry_b_id)', name='ck_comparison_chosen_entry_id'),
    sa.CheckConstraint('entry_a_id <> entry_b_id', name='ck_comparison_entry_a_not_entry_b'),
    sa.ForeignKeyConstraint(['chosen_entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entry_a_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entry_b_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_chosen_entry_id'), 'comparisons', ['chosen_entry_id'], unique=False)
    op.create_index(op.f('ix_comparisons_contest_id'), 'comparisons', ['contest_id'], unique=False)
    op.create_index(op.f('ix_comparisons_created_at'), 'comparisons', ['created_at'], unique=False)
    op.create_index(op.f('ix_comparisons_entry_a_id'), 'comparisons', ['entry_a_id'], unique=False)
    op.create_index(op.f('ix_comparisons_entry_b_id'), 'comparisons', ['entry_b_id'], unique=False)
    op.create_index(op.f('ix_comparisons_voter_user_id'), 'comparisons', ['voter_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparisons_voter_user_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_entry_b_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_entry_a_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_created_at'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_contest_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_chosen_entry_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_contest_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_contest_participations_user_id'), table_name='contest_participations')
    op.drop_index(op.f('ix_contest_participations_id'), table_name='contest_participations')
    op.drop_index(op.f('ix_contest_participations_contest_id'), table_name='contest_participations')
    op.drop_table('contest_participations')
    op.drop_index(op.f('ix_contests_title'), table_name='contests')
    op.drop_index(op.f('ix_contests_status'), table_name='contests')
    op.drop_table('contests')
    # ### end Alembic commands ###
