"""add thumbnail_url

Revision ID: e2a986acdb64
Revises: ff4962aa8000
Create Date: 2026-03-30 02:24:39.512953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a986acdb64'
down_revision: Union[str, Sequence[str], None] = 'ff4962aa8000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('thumbnail_url', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'thumbnail_url')
    # ### end Alembic commands ###
